import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thebatik.Co.Id",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative">
          <div className="bg-black w-full h-12 flex items-center justify-between px-4">
            <div className="flex items-center gap-4 mx-auto">
              <div className="text-white font-poppins text-sm">
                Summer Sale For All Batik Suits And Free Express Delivery - OFF
                50%!
              </div>
              <div className="text-white font-poppins font-semibold text-sm underline">
                ShopNow
              </div>
            </div>
          </div>
        </div>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
