import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";
// import Navbar from "@/components/navbar";
import { auth } from "@/auth";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | The Batik",
    default: "Home | The Batik",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

const Navbar = dynamic(() => import("@/components/navbar"), { ssr: true });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <Navbar session={session} />
          {children}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
